name: d
favicon: null
layout_spectrum: 0.64979
typography_spectrum: 0.35985
title: bentobox animorph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#de8f39'
    - '#2b4383'
    - '#668961'
    - '#8c4013'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
