name: d
favicon: null
layout_spectrum: 0.24762
typography_spectrum: 0.32598
title: bentobox animorph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78a0d4'
    - '#1e1101'
    - '#012d84'
    - '#d82306'
    - '#f8a59f'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
