name: d
favicon: null
layout_spectrum: 0.5305446931160986
typography_spectrum: 0.6621795003302395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9878252462949604
  lightness: 0.6831876279320568
  saturation: 0.05577641143463552
  rhythmicContrast: 0.2916757019702345
purpose: []
