name: d
favicon: null
layout_spectrum: 0.64979
typography_spectrum: 0.29918
title: bentobox animorph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0905'
    - '#0000d6'
    - '#f5f5e9'
    - '#916ba6'
    - '#442952'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
