name: d
favicon: null
layout_spectrum: 0.9216
typography_spectrum: 0.6621795003302395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0905'
    - '#0000d6'
    - '#f5f5e9'
    - '#916ba6'
    - '#442952'
  brandStrength: 0.9878252462949604
  lightness: 0.6831876279320568
  saturation: 0.05577641143463552
  rhythmicContrast: 0.2916757019702345
purpose: []
